// CAR DATABASE - 1000+ cars
// Each: { brand, model, gen }
var CAR_DATABASE = [
// LADA
{brand:"LADA",model:"Granta",gen:"2190"},{brand:"LADA",model:"Granta",gen:"FL 2018"},{brand:"LADA",model:"Vesta",gen:"GFL22"},{brand:"LADA",model:"Vesta",gen:"SW Cross"},{brand:"LADA",model:"Vesta",gen:"Sport"},{brand:"LADA",model:"Priora",gen:"2170"},{brand:"LADA",model:"Priora",gen:"2172 Coupe"},{brand:"LADA",model:"Kalina",gen:"1118"},{brand:"LADA",model:"Kalina",gen:"2192 Cross"},{brand:"LADA",model:"Niva",gen:"Legend 4x4"},{brand:"LADA",model:"Niva",gen:"Travel"},{brand:"LADA",model:"XRAY",gen:"Cross"},{brand:"LADA",model:"Largus",gen:"Cross"},{brand:"LADA",model:"2107",gen:"Classic"},{brand:"LADA",model:"2106",gen:"Classic"},{brand:"LADA",model:"2109",gen:"Samara"},{brand:"LADA",model:"2110",gen:"Sedan"},{brand:"LADA",model:"2112",gen:"Hatchback"},
// UAZ / GAZ / Moskevich / Aurus
{brand:"UAZ",model:"Patriot",gen:"2019+"},{brand:"UAZ",model:"Hunter",gen:"315195"},{brand:"UAZ",model:"Bukhanka",gen:"452"},{brand:"UAZ",model:"Pickup",gen:"2363"},{brand:"GAZ",model:"Volga",gen:"3110"},{brand:"GAZ",model:"Volga",gen:"31105"},{brand:"GAZ",model:"Volga",gen:"24"},{brand:"GAZ",model:"Chaika",gen:"14"},{brand:"GAZelle",model:"Next",gen:"A21R22"},{brand:"GAZelle",model:"Business",gen:"3302"},{brand:"\u041C\u043E\u0441\u043A\u0432\u0438\u0447",model:"3",gen:"2022"},{brand:"\u041C\u043E\u0441\u043A\u0432\u0438\u0447",model:"6",gen:"2024"},{brand:"\u041C\u043E\u0441\u043A\u0432\u0438\u0447",model:"412",gen:"Classic"},{brand:"\u041C\u043E\u0441\u043A\u0432\u0438\u0447",model:"2141",gen:"Aleko"},{brand:"Aurus",model:"Senat",gen:"S600"},{brand:"Aurus",model:"Senat",gen:"S700 Limousine"},{brand:"Aurus",model:"Komendant",gen:"SUV"},{brand:"Marussia",model:"B1",gen:"2008"},{brand:"Marussia",model:"B2",gen:"2010"},{brand:"ZIL",model:"4104",gen:"Limousine"},
// BMW
{brand:"BMW",model:"316i",gen:"E36"},{brand:"BMW",model:"318i",gen:"E46"},{brand:"BMW",model:"320i",gen:"E90"},{brand:"BMW",model:"320i",gen:"F30"},{brand:"BMW",model:"320i",gen:"G20"},{brand:"BMW",model:"325i",gen:"E36"},{brand:"BMW",model:"328i",gen:"F30"},{brand:"BMW",model:"330i",gen:"G20"},{brand:"BMW",model:"335i",gen:"E90"},{brand:"BMW",model:"340i",gen:"F30"},{brand:"BMW",model:"M3",gen:"E30"},{brand:"BMW",model:"M3",gen:"E36"},{brand:"BMW",model:"M3",gen:"E46"},{brand:"BMW",model:"M3",gen:"E90"},{brand:"BMW",model:"M3",gen:"F80"},{brand:"BMW",model:"M3 Competition",gen:"G80"},{brand:"BMW",model:"M3 CS",gen:"G80"},{brand:"BMW",model:"520i",gen:"E39"},{brand:"BMW",model:"520i",gen:"F10"},{brand:"BMW",model:"525d",gen:"E60"},{brand:"BMW",model:"530i",gen:"E60"},{brand:"BMW",model:"530d",gen:"G30"},{brand:"BMW",model:"540i",gen:"G30"},{brand:"BMW",model:"550i",gen:"F10"},{brand:"BMW",model:"M5",gen:"E39"},{brand:"BMW",model:"M5",gen:"E60"},{brand:"BMW",model:"M5",gen:"F10"},{brand:"BMW",model:"M5",gen:"F90"},{brand:"BMW",model:"M5 CS",gen:"F90"},{brand:"BMW",model:"730d",gen:"G11"},{brand:"BMW",model:"740Li",gen:"G70"},{brand:"BMW",model:"750i",gen:"E65"},{brand:"BMW",model:"760Li",gen:"G70"},{brand:"BMW",model:"M760Li",gen:"G11"},{brand:"BMW",model:"840i",gen:"G14"},{brand:"BMW",model:"M8 Competition",gen:"F92"},{brand:"BMW",model:"M4",gen:"F82"},{brand:"BMW",model:"M4 Competition",gen:"G82"},{brand:"BMW",model:"M4 CSL",gen:"G82"},{brand:"BMW",model:"M2",gen:"G87"},{brand:"BMW",model:"Z3",gen:"E36/7"},{brand:"BMW",model:"Z4 M40i",gen:"G29"},{brand:"BMW",model:"Z8",gen:"E52"},{brand:"BMW",model:"i3",gen:"I01"},{brand:"BMW",model:"i4 M50",gen:"G26"},{brand:"BMW",model:"iX M60",gen:"I20"},{brand:"BMW",model:"i7 xDrive60",gen:"G70"},{brand:"BMW",model:"X1",gen:"U11"},{brand:"BMW",model:"X3 M40i",gen:"G01"},{brand:"BMW",model:"X3 M",gen:"F97"},{brand:"BMW",model:"X4 M",gen:"F98"},{brand:"BMW",model:"X5 M60i",gen:"G05"},{brand:"BMW",model:"X5 M",gen:"F95"},{brand:"BMW",model:"X6 M",gen:"F96"},{brand:"BMW",model:"X7 M60i",gen:"G07"},{brand:"BMW",model:"XM Label Red",gen:"G09"},{brand:"BMW",model:"1M Coupe",gen:"E82"},
// Mercedes-Benz
{brand:"Mercedes-Benz",model:"C180",gen:"W202"},{brand:"Mercedes-Benz",model:"C200",gen:"W203"},{brand:"Mercedes-Benz",model:"C200",gen:"W204"},{brand:"Mercedes-Benz",model:"C200",gen:"W205"},{brand:"Mercedes-Benz",model:"C200",gen:"W206"},{brand:"Mercedes-Benz",model:"C300",gen:"W206"},{brand:"Mercedes-Benz",model:"C63 AMG",gen:"W204"},{brand:"Mercedes-AMG",model:"C63 S",gen:"W205"},{brand:"Mercedes-AMG",model:"C63 S E",gen:"W206"},{brand:"Mercedes-Benz",model:"E200",gen:"W210"},{brand:"Mercedes-Benz",model:"E200",gen:"W211"},{brand:"Mercedes-Benz",model:"E200",gen:"W212"},{brand:"Mercedes-Benz",model:"E200",gen:"W213"},{brand:"Mercedes-Benz",model:"E300",gen:"W214"},{brand:"Mercedes-Benz",model:"E55 AMG",gen:"W211"},{brand:"Mercedes-AMG",model:"E63 S",gen:"W213"},{brand:"Mercedes-Benz",model:"S350",gen:"W220"},{brand:"Mercedes-Benz",model:"S500",gen:"W221"},{brand:"Mercedes-Benz",model:"S500",gen:"W222"},{brand:"Mercedes-Benz",model:"S500",gen:"W223"},{brand:"Mercedes-Benz",model:"S600",gen:"W140"},{brand:"Mercedes-Benz",model:"S680 Maybach",gen:"W223"},{brand:"Mercedes-Maybach",model:"GLS 600",gen:"X167"},{brand:"Mercedes-Benz",model:"CLS 53 AMG",gen:"C257"},{brand:"Mercedes-Benz",model:"CLA 250",gen:"C118"},{brand:"Mercedes-Benz",model:"CLE 300",gen:"C236"},{brand:"Mercedes-AMG",model:"GT 63 S",gen:"X290"},{brand:"Mercedes-AMG",model:"GT Black Series",gen:"C190"},{brand:"Mercedes-AMG",model:"GT R",gen:"C190"},{brand:"Mercedes-AMG",model:"SL 63",gen:"R232"},{brand:"Mercedes-AMG",model:"One",gen:"2022"},{brand:"Mercedes-Benz",model:"SLR McLaren",gen:"C199"},{brand:"Mercedes-Benz",model:"SLS AMG",gen:"C197"},{brand:"Mercedes-Benz",model:"G500",gen:"W463"},{brand:"Mercedes-Benz",model:"G63 AMG",gen:"W463"},{brand:"Mercedes-Benz",model:"G65 AMG",gen:"W463"},{brand:"Mercedes-Benz",model:"G500 4x4\u00B2",gen:"W463"},{brand:"Mercedes-Benz",model:"GLA 250",gen:"H247"},{brand:"Mercedes-Benz",model:"GLB 250",gen:"X247"},{brand:"Mercedes-Benz",model:"GLC 300",gen:"X254"},{brand:"Mercedes-AMG",model:"GLC 63 S",gen:"X254"},{brand:"Mercedes-Benz",model:"GLE 450",gen:"V167"},{brand:"Mercedes-AMG",model:"GLE 63 S",gen:"V167"},{brand:"Mercedes-Benz",model:"GLS 450",gen:"X167"},{brand:"Mercedes-Benz",model:"EQS 580",gen:"V297"},{brand:"Mercedes-Benz",model:"EQE SUV",gen:"X294"},{brand:"Mercedes-Benz",model:"EQA 250",gen:"H243"},{brand:"Mercedes-Benz",model:"EQB 350",gen:"X243"},{brand:"Mercedes-Benz",model:"CLK 55 AMG",gen:"W209"},
// Audi
{brand:"Audi",model:"A3",gen:"8Y"},{brand:"Audi",model:"A3",gen:"8P"},{brand:"Audi",model:"S3",gen:"8Y"},{brand:"Audi",model:"RS3",gen:"8Y"},{brand:"Audi",model:"A4",gen:"B5"},{brand:"Audi",model:"A4",gen:"B6"},{brand:"Audi",model:"A4",gen:"B7"},{brand:"Audi",model:"A4",gen:"B8"},{brand:"Audi",model:"A4",gen:"B9"},{brand:"Audi",model:"S4",gen:"B9"},{brand:"Audi",model:"RS4 Avant",gen:"B9"},{brand:"Audi",model:"A5 Sportback",gen:"F5"},{brand:"Audi",model:"S5",gen:"F5"},{brand:"Audi",model:"RS5",gen:"F5"},{brand:"Audi",model:"A6",gen:"C5"},{brand:"Audi",model:"A6",gen:"C6"},{brand:"Audi",model:"A6",gen:"C7"},{brand:"Audi",model:"A6",gen:"C8"},{brand:"Audi",model:"S6",gen:"C8"},{brand:"Audi",model:"RS6 Avant",gen:"C8"},{brand:"Audi",model:"RS6 Avant",gen:"C7"},{brand:"Audi",model:"A7 Sportback",gen:"C8"},{brand:"Audi",model:"RS7 Sportback",gen:"C8"},{brand:"Audi",model:"A8",gen:"D3"},{brand:"Audi",model:"A8 Long",gen:"D5"},{brand:"Audi",model:"S8",gen:"D5"},{brand:"Audi",model:"TT",gen:"8N"},{brand:"Audi",model:"TT RS",gen:"8S"},{brand:"Audi",model:"R8 V10",gen:"Type 42"},{brand:"Audi",model:"R8 V10 Performance",gen:"Type 4S"},{brand:"Audi",model:"Q3 Sportback",gen:"F3"},{brand:"Audi",model:"Q5",gen:"FY"},{brand:"Audi",model:"SQ5",gen:"FY"},{brand:"Audi",model:"Q7 55 TFSI",gen:"4M"},{brand:"Audi",model:"SQ7",gen:"4M"},{brand:"Audi",model:"Q8",gen:"4MN"},{brand:"Audi",model:"RS Q8",gen:"4MN"},{brand:"Audi",model:"e-tron GT",gen:"J1"},{brand:"Audi",model:"RS e-tron GT",gen:"J1"},{brand:"Audi",model:"Q8 e-tron",gen:"GE"},{brand:"Audi",model:"Q4 e-tron",gen:"F4B"},
// Volkswagen
{brand:"Volkswagen",model:"Golf",gen:"Mk4"},{brand:"Volkswagen",model:"Golf",gen:"Mk5"},{brand:"Volkswagen",model:"Golf",gen:"Mk6"},{brand:"Volkswagen",model:"Golf",gen:"Mk7"},{brand:"Volkswagen",model:"Golf GTI",gen:"Mk8"},{brand:"Volkswagen",model:"Golf R",gen:"Mk8"},{brand:"Volkswagen",model:"Polo",gen:"Mk6"},{brand:"Volkswagen",model:"Polo GTI",gen:"AW"},{brand:"Volkswagen",model:"Jetta",gen:"Mk7"},{brand:"Volkswagen",model:"Passat",gen:"B5"},{brand:"Volkswagen",model:"Passat",gen:"B6"},{brand:"Volkswagen",model:"Passat",gen:"B7"},{brand:"Volkswagen",model:"Passat",gen:"B8"},{brand:"Volkswagen",model:"Arteon",gen:"3H"},{brand:"Volkswagen",model:"Arteon R",gen:"3H"},{brand:"Volkswagen",model:"Tiguan",gen:"AD"},{brand:"Volkswagen",model:"Tiguan",gen:"Mk2 FL"},{brand:"Volkswagen",model:"Touareg",gen:"CR"},{brand:"Volkswagen",model:"Touareg R",gen:"CR"},{brand:"Volkswagen",model:"T-Roc R",gen:"A11"},{brand:"Volkswagen",model:"Scirocco R",gen:"Mk3"},{brand:"Volkswagen",model:"Phaeton",gen:"3D"},{brand:"Volkswagen",model:"ID.3",gen:"E11"},{brand:"Volkswagen",model:"ID.4 GTX",gen:"E21"},{brand:"Volkswagen",model:"ID.7",gen:"E71"},{brand:"Volkswagen",model:"ID. Buzz",gen:"AD1"},{brand:"Volkswagen",model:"Up! GTI",gen:"AA"},
// Porsche
{brand:"Porsche",model:"911 Carrera",gen:"964"},{brand:"Porsche",model:"911 Carrera",gen:"993"},{brand:"Porsche",model:"911 Carrera",gen:"996"},{brand:"Porsche",model:"911 Carrera S",gen:"997"},{brand:"Porsche",model:"911 Carrera S",gen:"991"},{brand:"Porsche",model:"911 Carrera S",gen:"992"},{brand:"Porsche",model:"911 GT3",gen:"996"},{brand:"Porsche",model:"911 GT3",gen:"997"},{brand:"Porsche",model:"911 GT3",gen:"991"},{brand:"Porsche",model:"911 GT3 RS",gen:"992"},{brand:"Porsche",model:"911 Turbo S",gen:"992"},{brand:"Porsche",model:"911 Turbo S",gen:"991"},{brand:"Porsche",model:"911 GT2 RS",gen:"991"},{brand:"Porsche",model:"911 S/T",gen:"992"},{brand:"Porsche",model:"911 Dakar",gen:"992"},{brand:"Porsche",model:"918 Spyder",gen:"2013"},{brand:"Porsche",model:"Carrera GT",gen:"980"},{brand:"Porsche",model:"Boxster",gen:"986"},{brand:"Porsche",model:"718 Boxster S",gen:"982"},{brand:"Porsche",model:"718 Cayman GT4",gen:"982"},{brand:"Porsche",model:"718 Cayman GT4 RS",gen:"982"},{brand:"Porsche",model:"Panamera",gen:"970"},{brand:"Porsche",model:"Panamera Turbo S",gen:"971"},{brand:"Porsche",model:"Panamera Turbo S E",gen:"971 FL"},{brand:"Porsche",model:"Cayenne",gen:"E1"},{brand:"Porsche",model:"Cayenne Turbo",gen:"E3"},{brand:"Porsche",model:"Cayenne Turbo GT",gen:"E3"},{brand:"Porsche",model:"Macan",gen:"95B"},{brand:"Porsche",model:"Macan T",gen:"95B FL"},{brand:"Porsche",model:"Macan EV",gen:"J1"},{brand:"Porsche",model:"Taycan Turbo S",gen:"Y1A"},{brand:"Porsche",model:"Taycan GTS",gen:"Y1A"},{brand:"Porsche",model:"Taycan Cross Turismo",gen:"Y1B"},
// Opel
{brand:"Opel",model:"Astra",gen:"J"},{brand:"Opel",model:"Astra",gen:"K"},{brand:"Opel",model:"Astra",gen:"L"},{brand:"Opel",model:"Corsa",gen:"E"},{brand:"Opel",model:"Corsa",gen:"F"},{brand:"Opel",model:"Insignia",gen:"B"},{brand:"Opel",model:"Mokka",gen:"II"},{brand:"Opel",model:"Grandland",gen:"FL"},{brand:"Opel",model:"Speedster",gen:"2001"},
// Toyota
{brand:"Toyota",model:"Camry",gen:"XV30"},{brand:"Toyota",model:"Camry",gen:"XV40"},{brand:"Toyota",model:"Camry",gen:"XV50"},{brand:"Toyota",model:"Camry",gen:"XV70"},{brand:"Toyota",model:"Corolla",gen:"E120"},{brand:"Toyota",model:"Corolla",gen:"E150"},{brand:"Toyota",model:"Corolla",gen:"E170"},{brand:"Toyota",model:"Corolla",gen:"E210"},{brand:"Toyota",model:"Corolla Cross",gen:"XG10"},{brand:"Toyota",model:"Yaris",gen:"XP210"},{brand:"Toyota",model:"Yaris GR",gen:"GXPA16"},{brand:"Toyota",model:"Avensis",gen:"T250"},{brand:"Toyota",model:"Crown",gen:"Crossover S235"},{brand:"Toyota",model:"Century",gen:"GRMN V12"},{brand:"Toyota",model:"Mark II",gen:"JZX100"},{brand:"Toyota",model:"Chaser",gen:"JZX100"},{brand:"Toyota",model:"Supra",gen:"A70"},{brand:"Toyota",model:"Supra",gen:"A80"},{brand:"Toyota",model:"Supra",gen:"A90"},{brand:"Toyota",model:"GR86",gen:"ZN8"},{brand:"Toyota",model:"MR2",gen:"SW20"},{brand:"Toyota",model:"Celica",gen:"T230"},{brand:"Toyota",model:"RAV4",gen:"XA50"},{brand:"Toyota",model:"RAV4",gen:"XA40"},{brand:"Toyota",model:"Highlander",gen:"XU70"},{brand:"Toyota",model:"Land Cruiser",gen:"J200"},{brand:"Toyota",model:"Land Cruiser",gen:"J300"},{brand:"Toyota",model:"Land Cruiser Prado",gen:"J120"},{brand:"Toyota",model:"Land Cruiser Prado",gen:"J150"},{brand:"Toyota",model:"Land Cruiser Prado",gen:"J250"},{brand:"Toyota",model:"4Runner",gen:"N280"},{brand:"Toyota",model:"Fortuner",gen:"AN160"},{brand:"Toyota",model:"Hilux",gen:"AN120"},{brand:"Toyota",model:"Tundra",gen:"XK70"},{brand:"Toyota",model:"Sequoia",gen:"XK80"},{brand:"Toyota",model:"Mirai",gen:"JPD20"},{brand:"Toyota",model:"bZ4X",gen:"EA10"},{brand:"Toyota",model:"Alphard",gen:"AGH40"},{brand:"Toyota",model:"Hiace",gen:"H300"},
// Lexus
{brand:"Lexus",model:"IS 250",gen:"XE20"},{brand:"Lexus",model:"IS 300",gen:"XE30"},{brand:"Lexus",model:"IS 500 F Sport",gen:"XE30 FL"},{brand:"Lexus",model:"ES 350",gen:"XV70"},{brand:"Lexus",model:"GS 350",gen:"L10"},{brand:"Lexus",model:"GS F",gen:"URL10"},{brand:"Lexus",model:"LS 500h",gen:"XF50"},{brand:"Lexus",model:"LS 460",gen:"XF40"},{brand:"Lexus",model:"LC 500",gen:"URZ100"},{brand:"Lexus",model:"LC 500h",gen:"GWZ100"},{brand:"Lexus",model:"RC F",gen:"USC10"},{brand:"Lexus",model:"LFA",gen:"LFA10"},{brand:"Lexus",model:"RX 350",gen:"AL20"},{brand:"Lexus",model:"RX 500h",gen:"AL25"},{brand:"Lexus",model:"NX 350h",gen:"AZ25"},{brand:"Lexus",model:"UX 300e",gen:"ZA10"},{brand:"Lexus",model:"LX 600",gen:"VJA310"},{brand:"Lexus",model:"LX 570",gen:"URJ201"},{brand:"Lexus",model:"GX 460",gen:"URJ150"},{brand:"Lexus",model:"GX 550",gen:"GX3"},{brand:"Lexus",model:"RZ 450e",gen:"XAA10"},
// Nissan
{brand:"Nissan",model:"Skyline GT-R",gen:"R32"},{brand:"Nissan",model:"Skyline GT-R",gen:"R33"},{brand:"Nissan",model:"Skyline GT-R",gen:"R34"},{brand:"Nissan",model:"GT-R",gen:"R35"},{brand:"Nissan",model:"GT-R Nismo",gen:"R35"},{brand:"Nissan",model:"350Z",gen:"Z33"},{brand:"Nissan",model:"370Z",gen:"Z34"},{brand:"Nissan",model:"370Z Nismo",gen:"Z34"},{brand:"Nissan",model:"Z",gen:"RZ34"},{brand:"Nissan",model:"Z Nismo",gen:"RZ34"},{brand:"Nissan",model:"Silvia",gen:"S13"},{brand:"Nissan",model:"Silvia",gen:"S14"},{brand:"Nissan",model:"Silvia",gen:"S15"},{brand:"Nissan",model:"Altima",gen:"L34"},{brand:"Nissan",model:"Maxima",gen:"A36"},{brand:"Nissan",model:"Sentra",gen:"B18"},{brand:"Nissan",model:"X-Trail",gen:"T32"},{brand:"Nissan",model:"X-Trail",gen:"T33"},{brand:"Nissan",model:"Qashqai",gen:"J11"},{brand:"Nissan",model:"Qashqai",gen:"J12"},{brand:"Nissan",model:"Pathfinder",gen:"R53"},{brand:"Nissan",model:"Patrol",gen:"Y61"},{brand:"Nissan",model:"Patrol",gen:"Y62"},{brand:"Nissan",model:"Murano",gen:"Z52"},{brand:"Nissan",model:"Juke",gen:"F16"},{brand:"Nissan",model:"Leaf",gen:"ZE1"},{brand:"Nissan",model:"Ariya",gen:"FE0"},{brand:"Nissan",model:"Note e-Power",gen:"E13"},
// Infiniti
{brand:"Infiniti",model:"G35",gen:"V35"},{brand:"Infiniti",model:"G37",gen:"V36"},{brand:"Infiniti",model:"Q50",gen:"V37"},{brand:"Infiniti",model:"Q50 Red Sport",gen:"V37 FL"},{brand:"Infiniti",model:"Q60",gen:"CV37"},{brand:"Infiniti",model:"Q60 Red Sport",gen:"CV37"},{brand:"Infiniti",model:"Q70",gen:"Y51"},{brand:"Infiniti",model:"FX50",gen:"S51"},{brand:"Infiniti",model:"QX50",gen:"J55"},{brand:"Infiniti",model:"QX55",gen:"J55"},{brand:"Infiniti",model:"QX60",gen:"L51"},{brand:"Infiniti",model:"QX70",gen:"S51"},{brand:"Infiniti",model:"QX80",gen:"Z62"},
// Honda
{brand:"Honda",model:"Civic",gen:"EK"},{brand:"Honda",model:"Civic",gen:"EP"},{brand:"Honda",model:"Civic",gen:"FD"},{brand:"Honda",model:"Civic",gen:"FK7"},{brand:"Honda",model:"Civic",gen:"FL1"},{brand:"Honda",model:"Civic Type R",gen:"EP3"},{brand:"Honda",model:"Civic Type R",gen:"FN2"},{brand:"Honda",model:"Civic Type R",gen:"FK2"},{brand:"Honda",model:"Civic Type R",gen:"FK8"},{brand:"Honda",model:"Civic Type R",gen:"FL5"},{brand:"Honda",model:"Accord",gen:"CL7"},{brand:"Honda",model:"Accord",gen:"CU2"},{brand:"Honda",model:"Accord",gen:"CV"},{brand:"Honda",model:"Integra Type R",gen:"DC2"},{brand:"Honda",model:"Integra",gen:"DE"},{brand:"Honda",model:"S2000",gen:"AP1"},{brand:"Honda",model:"S2000",gen:"AP2"},{brand:"Honda",model:"NSX",gen:"NA1"},{brand:"Honda",model:"NSX Type S",gen:"NC1"},{brand:"Honda",model:"Prelude",gen:"BB6"},{brand:"Honda",model:"Fit / Jazz",gen:"GR"},{brand:"Honda",model:"HR-V",gen:"RV"},{brand:"Honda",model:"CR-V",gen:"RW"},{brand:"Honda",model:"CR-V",gen:"RE"},{brand:"Honda",model:"Pilot",gen:"YF7"},{brand:"Honda",model:"Passport",gen:"YG"},{brand:"Honda",model:"e",gen:"2020"},{brand:"Honda",model:"e:Ny1",gen:"2024"},
// Mazda
{brand:"Mazda",model:"MX-5",gen:"NA"},{brand:"Mazda",model:"MX-5",gen:"NB"},{brand:"Mazda",model:"MX-5",gen:"NC"},{brand:"Mazda",model:"MX-5",gen:"ND"},{brand:"Mazda",model:"RX-7",gen:"FC"},{brand:"Mazda",model:"RX-7",gen:"FD"},{brand:"Mazda",model:"RX-8",gen:"SE3P"},{brand:"Mazda",model:"3",gen:"BK"},{brand:"Mazda",model:"3",gen:"BL"},{brand:"Mazda",model:"3",gen:"BM"},{brand:"Mazda",model:"3",gen:"BP"},{brand:"Mazda",model:"6",gen:"GG"},{brand:"Mazda",model:"6",gen:"GH"},{brand:"Mazda",model:"6",gen:"GJ"},{brand:"Mazda",model:"CX-3",gen:"DK"},{brand:"Mazda",model:"CX-5",gen:"KE"},{brand:"Mazda",model:"CX-5",gen:"KF"},{brand:"Mazda",model:"CX-30",gen:"DM"},{brand:"Mazda",model:"CX-60",gen:"KH"},{brand:"Mazda",model:"CX-90 PHEV",gen:"KJ"},{brand:"Mazda",model:"MX-30",gen:"DR"},
// Subaru
{brand:"Subaru",model:"Impreza WRX",gen:"GC8"},{brand:"Subaru",model:"Impreza WRX",gen:"GDB"},{brand:"Subaru",model:"Impreza WRX STI",gen:"GRB"},{brand:"Subaru",model:"WRX STI",gen:"VA"},{brand:"Subaru",model:"WRX",gen:"VB"},{brand:"Subaru",model:"BRZ",gen:"ZC6"},{brand:"Subaru",model:"BRZ",gen:"ZD8"},{brand:"Subaru",model:"Legacy",gen:"BN"},{brand:"Subaru",model:"Impreza",gen:"GK"},{brand:"Subaru",model:"Crosstrek",gen:"GU"},{brand:"Subaru",model:"Forester",gen:"SJ"},{brand:"Subaru",model:"Forester",gen:"SK"},{brand:"Subaru",model:"Outback",gen:"BS"},{brand:"Subaru",model:"Outback",gen:"BT"},{brand:"Subaru",model:"Solterra",gen:"XEAM10"},{brand:"Subaru",model:"SVX",gen:"CX"},
// Mitsubishi
{brand:"Mitsubishi",model:"Lancer Evo VI",gen:"CP9A"},{brand:"Mitsubishi",model:"Lancer Evo VIII",gen:"CT9A"},{brand:"Mitsubishi",model:"Lancer Evo IX",gen:"CT9A"},{brand:"Mitsubishi",model:"Lancer Evo X",gen:"CZ4A"},{brand:"Mitsubishi",model:"Lancer",gen:"CY"},{brand:"Mitsubishi",model:"Eclipse",gen:"D30"},{brand:"Mitsubishi",model:"Eclipse Cross",gen:"GK"},{brand:"Mitsubishi",model:"3000GT",gen:"Z16A"},{brand:"Mitsubishi",model:"GTO",gen:"Z15A"},{brand:"Mitsubishi",model:"Outlander",gen:"GF"},{brand:"Mitsubishi",model:"Outlander PHEV",gen:"GN"},{brand:"Mitsubishi",model:"ASX",gen:"GA"},{brand:"Mitsubishi",model:"Pajero",gen:"V80"},{brand:"Mitsubishi",model:"Pajero Sport",gen:"KS"},{brand:"Mitsubishi",model:"L200",gen:"KL"},{brand:"Mitsubishi",model:"Delica D:5",gen:"CV5W"},
// Suzuki
{brand:"Suzuki",model:"Swift Sport",gen:"ZC33S"},{brand:"Suzuki",model:"Jimny",gen:"JB74"},{brand:"Suzuki",model:"Vitara",gen:"LY"},{brand:"Suzuki",model:"S-Cross",gen:"YEA"},{brand:"Suzuki",model:"Ignis",gen:"MF"},{brand:"Suzuki",model:"Alto Works",gen:"HA36S"},{brand:"Suzuki",model:"Cappuccino",gen:"EA11R"},
// Hyundai
{brand:"Hyundai",model:"Solaris",gen:"HCR"},{brand:"Hyundai",model:"Accent",gen:"LC"},{brand:"Hyundai",model:"Elantra",gen:"CN7"},{brand:"Hyundai",model:"Elantra N",gen:"CN7"},{brand:"Hyundai",model:"Sonata",gen:"DN8"},{brand:"Hyundai",model:"Sonata",gen:"YF"},{brand:"Hyundai",model:"Sonata",gen:"LF"},{brand:"Hyundai",model:"Grandeur",gen:"GN7"},{brand:"Hyundai",model:"Genesis Coupe",gen:"BK"},{brand:"Hyundai",model:"Veloster N",gen:"JS"},{brand:"Hyundai",model:"i20 N",gen:"BC3"},{brand:"Hyundai",model:"i30 N",gen:"PD"},{brand:"Hyundai",model:"i30",gen:"GD"},{brand:"Hyundai",model:"Creta",gen:"SU2"},{brand:"Hyundai",model:"Tucson",gen:"TL"},{brand:"Hyundai",model:"Tucson",gen:"NX4"},{brand:"Hyundai",model:"Santa Fe",gen:"TM"},{brand:"Hyundai",model:"Santa Fe",gen:"MX5"},{brand:"Hyundai",model:"Palisade",gen:"LX2"},{brand:"Hyundai",model:"Kona",gen:"SX2"},{brand:"Hyundai",model:"IONIQ 5",gen:"NE"},{brand:"Hyundai",model:"IONIQ 5 N",gen:"NE"},{brand:"Hyundai",model:"IONIQ 6",gen:"CE"},{brand:"Hyundai",model:"Staria",gen:"US4"},
// Kia
{brand:"Kia",model:"Rio",gen:"FB"},{brand:"Kia",model:"Rio",gen:"YB"},{brand:"Kia",model:"Ceed",gen:"CD"},{brand:"Kia",model:"Ceed GT",gen:"CD"},{brand:"Kia",model:"Cerato",gen:"BD"},{brand:"Kia",model:"K5",gen:"DL3"},{brand:"Kia",model:"K5 GT",gen:"DL3"},{brand:"Kia",model:"K8",gen:"GL3"},{brand:"Kia",model:"K9",gen:"RJ"},{brand:"Kia",model:"Stinger GT",gen:"CK"},{brand:"Kia",model:"Seltos",gen:"SP2"},{brand:"Kia",model:"Sportage",gen:"NQ5"},{brand:"Kia",model:"Sportage",gen:"QL"},{brand:"Kia",model:"Sorento",gen:"MQ4"},{brand:"Kia",model:"Telluride",gen:"ON"},{brand:"Kia",model:"Mohave",gen:"HM"},{brand:"Kia",model:"Carnival",gen:"KA4"},{brand:"Kia",model:"EV6 GT",gen:"CV"},{brand:"Kia",model:"EV9 GT-Line",gen:"MV"},{brand:"Kia",model:"Niro EV",gen:"SG2"},{brand:"Kia",model:"Soul",gen:"SK3"},
// Genesis
{brand:"Genesis",model:"G70",gen:"IK"},{brand:"Genesis",model:"G70 3.3T",gen:"IK"},{brand:"Genesis",model:"G80",gen:"RG3"},{brand:"Genesis",model:"G80 Sport",gen:"RG3"},{brand:"Genesis",model:"G90",gen:"RS4"},{brand:"Genesis",model:"G90 Long",gen:"HI"},{brand:"Genesis",model:"GV60",gen:"JW"},{brand:"Genesis",model:"GV70",gen:"JK1"},{brand:"Genesis",model:"GV70 Electrified",gen:"JK1"},{brand:"Genesis",model:"GV80",gen:"JX1"},{brand:"Genesis",model:"GV80 Coupe",gen:"JX1"},{brand:"Genesis",model:"X Concept",gen:"2021"},
// SsangYong
{brand:"SsangYong",model:"Actyon Sports",gen:"QJ"},{brand:"SsangYong",model:"Rexton",gen:"Y450"},{brand:"SsangYong",model:"Torres",gen:"KR10"},{brand:"SsangYong",model:"Korando",gen:"C300"},
// Ford
{brand:"Ford",model:"Mustang GT",gen:"S197"},{brand:"Ford",model:"Mustang GT",gen:"S550"},{brand:"Ford",model:"Mustang GT",gen:"S650"},{brand:"Ford",model:"Mustang Shelby GT350",gen:"S550"},{brand:"Ford",model:"Mustang Shelby GT500",gen:"S550"},{brand:"Ford",model:"Mustang Mach 1",gen:"S550"},{brand:"Ford",model:"Mustang Mach-E GT",gen:"2021"},{brand:"Ford",model:"Mustang Dark Horse",gen:"S650"},{brand:"Ford",model:"Focus ST",gen:"Mk3"},{brand:"Ford",model:"Focus RS",gen:"Mk3"},{brand:"Ford",model:"Focus ST",gen:"Mk4"},{brand:"Ford",model:"Fiesta ST",gen:"Mk8"},{brand:"Ford",model:"Fusion / Mondeo",gen:"CD4"},{brand:"Ford",model:"Mondeo",gen:"Mk5"},{brand:"Ford",model:"Taurus",gen:"D5"},{brand:"Ford",model:"F-150",gen:"XIV"},{brand:"Ford",model:"F-150 Raptor",gen:"XIV"},{brand:"Ford",model:"F-150 Raptor R",gen:"XIV"},{brand:"Ford",model:"F-150 Lightning",gen:"EV"},{brand:"Ford",model:"Ranger Raptor",gen:"P703"},{brand:"Ford",model:"Bronco",gen:"6th Gen"},{brand:"Ford",model:"Bronco Raptor",gen:"6th Gen"},{brand:"Ford",model:"Explorer",gen:"U625"},{brand:"Ford",model:"Expedition",gen:"U553"},{brand:"Ford",model:"Edge",gen:"CD4 FL"},{brand:"Ford",model:"Escape / Kuga",gen:"CX482"},{brand:"Ford",model:"Puma ST",gen:"2023"},{brand:"Ford",model:"GT",gen:"2017"},{brand:"Ford",model:"GT Mk IV",gen:"2023"},{brand:"Ford",model:"GT40",gen:"Mk I"},
// Chevrolet
{brand:"Chevrolet",model:"Corvette",gen:"C5"},{brand:"Chevrolet",model:"Corvette",gen:"C6"},{brand:"Chevrolet",model:"Corvette Z06",gen:"C6"},{brand:"Chevrolet",model:"Corvette ZR1",gen:"C6"},{brand:"Chevrolet",model:"Corvette Stingray",gen:"C7"},{brand:"Chevrolet",model:"Corvette Z06",gen:"C7"},{brand:"Chevrolet",model:"Corvette Stingray",gen:"C8"},{brand:"Chevrolet",model:"Corvette Z06",gen:"C8"},{brand:"Chevrolet",model:"Corvette E-Ray",gen:"C8"},{brand:"Chevrolet",model:"Corvette ZR1",gen:"C8"},{brand:"Chevrolet",model:"Camaro SS",gen:"5th Gen"},{brand:"Chevrolet",model:"Camaro ZL1",gen:"6th Gen"},{brand:"Chevrolet",model:"Camaro ZL1 1LE",gen:"6th Gen"},{brand:"Chevrolet",model:"Impala",gen:"10th Gen"},{brand:"Chevrolet",model:"Malibu",gen:"9th Gen"},{brand:"Chevrolet",model:"Cruze",gen:"J400"},{brand:"Chevrolet",model:"Tahoe",gen:"GMT1YC"},{brand:"Chevrolet",model:"Suburban",gen:"GMT1YC"},{brand:"Chevrolet",model:"Silverado",gen:"T1XX"},{brand:"Chevrolet",model:"Silverado ZR2",gen:"T1XX"},{brand:"Chevrolet",model:"Colorado ZR2",gen:"3GT"},{brand:"Chevrolet",model:"Blazer EV",gen:"2024"},{brand:"Chevrolet",model:"Equinox EV RS",gen:"2024"},{brand:"Chevrolet",model:"Bolt EUV",gen:"2023"},{brand:"Chevrolet",model:"Traverse",gen:"2024"},
// Dodge
{brand:"Dodge",model:"Challenger SRT Hellcat",gen:"LC"},{brand:"Dodge",model:"Challenger SRT Demon",gen:"LC"},{brand:"Dodge",model:"Challenger SRT Demon 170",gen:"LC"},{brand:"Dodge",model:"Challenger Redeye",gen:"LC"},{brand:"Dodge",model:"Charger SRT Hellcat",gen:"LD"},{brand:"Dodge",model:"Charger Daytona EV",gen:"2024"},{brand:"Dodge",model:"Viper",gen:"ZB II"},{brand:"Dodge",model:"Viper ACR",gen:"GTS-R"},{brand:"Dodge",model:"Durango SRT 392",gen:"WD"},{brand:"Dodge",model:"Durango SRT Hellcat",gen:"WD"},{brand:"Dodge",model:"Ram 1500 TRX",gen:"DT"},
// Cadillac
{brand:"Cadillac",model:"CTS-V",gen:"3rd Gen"},{brand:"Cadillac",model:"CT4-V Blackwing",gen:"2022"},{brand:"Cadillac",model:"CT5-V Blackwing",gen:"2022"},{brand:"Cadillac",model:"CT6",gen:"Platinum"},{brand:"Cadillac",model:"Escalade",gen:"GMT1XX"},{brand:"Cadillac",model:"Escalade V",gen:"GMT1XX"},{brand:"Cadillac",model:"Escalade V ESV",gen:"GMT1XX"},{brand:"Cadillac",model:"XT6",gen:"C1XX"},{brand:"Cadillac",model:"Lyriq",gen:"2023"},{brand:"Cadillac",model:"Celestiq",gen:"2024"},
// Jeep
{brand:"Jeep",model:"Wrangler Rubicon",gen:"JL"},{brand:"Jeep",model:"Wrangler Rubicon 392",gen:"JL"},{brand:"Jeep",model:"Wrangler Sahara",gen:"JK"},{brand:"Jeep",model:"Gladiator Rubicon",gen:"JT"},{brand:"Jeep",model:"Grand Cherokee",gen:"WK2"},{brand:"Jeep",model:"Grand Cherokee L",gen:"WL"},{brand:"Jeep",model:"Grand Cherokee 4xe",gen:"WL"},{brand:"Jeep",model:"Grand Wagoneer",gen:"WS"},{brand:"Jeep",model:"Cherokee",gen:"KL"},{brand:"Jeep",model:"Compass",gen:"MP"},{brand:"Jeep",model:"Renegade",gen:"BU"},{brand:"Jeep",model:"Wagoneer S EV",gen:"2024"},
// Tesla
{brand:"Tesla",model:"Model S",gen:"Plaid"},{brand:"Tesla",model:"Model S",gen:"Long Range"},{brand:"Tesla",model:"Model S",gen:"P100D"},{brand:"Tesla",model:"Model 3",gen:"Performance"},{brand:"Tesla",model:"Model 3",gen:"Highland"},{brand:"Tesla",model:"Model X",gen:"Plaid"},{brand:"Tesla",model:"Model X",gen:"Long Range"},{brand:"Tesla",model:"Model Y",gen:"Long Range"},{brand:"Tesla",model:"Model Y",gen:"Performance"},{brand:"Tesla",model:"Cybertruck",gen:"Foundation"},{brand:"Tesla",model:"Cybertruck",gen:"Cyberbeast"},{brand:"Tesla",model:"Roadster",gen:"1st Gen"},{brand:"Tesla",model:"Roadster",gen:"2.0 2025"},
// Lincoln / GMC / Rivian / Lucid / Chrysler / Ram
{brand:"Lincoln",model:"Continental",gen:"10th Gen"},{brand:"Lincoln",model:"Navigator",gen:"U554"},{brand:"Lincoln",model:"Aviator",gen:"CD6"},{brand:"Lincoln",model:"Corsair",gen:"C2"},{brand:"GMC",model:"Sierra 1500",gen:"T1XX"},{brand:"GMC",model:"Sierra Denali Ultimate",gen:"T1XX"},{brand:"GMC",model:"Yukon Denali",gen:"GMT1YC"},{brand:"GMC",model:"Hummer EV",gen:"2022"},{brand:"GMC",model:"Hummer EV SUV",gen:"2024"},{brand:"GMC",model:"Canyon AT4X",gen:"3GT"},{brand:"Rivian",model:"R1T",gen:"2022"},{brand:"Rivian",model:"R1S",gen:"2022"},{brand:"Rivian",model:"R2",gen:"2026"},{brand:"Lucid",model:"Air Sapphire",gen:"2024"},{brand:"Lucid",model:"Air Grand Touring",gen:"2023"},{brand:"Lucid",model:"Gravity",gen:"2025"},{brand:"Chrysler",model:"300 SRT8",gen:"LX II"},{brand:"Chrysler",model:"Pacifica",gen:"RU"},{brand:"Ram",model:"1500 TRX",gen:"DT"},{brand:"Ram",model:"1500 Laramie",gen:"DT"},
// Ferrari
{brand:"Ferrari",model:"250 GTO",gen:"1962"},{brand:"Ferrari",model:"F40",gen:"1987"},{brand:"Ferrari",model:"F50",gen:"1995"},{brand:"Ferrari",model:"Enzo",gen:"2002"},{brand:"Ferrari",model:"LaFerrari",gen:"2013"},{brand:"Ferrari",model:"LaFerrari Aperta",gen:"2016"},{brand:"Ferrari",model:"Daytona SP3",gen:"2022"},{brand:"Ferrari",model:"360 Modena",gen:"F131"},{brand:"Ferrari",model:"430 Scuderia",gen:"F131"},{brand:"Ferrari",model:"458 Italia",gen:"F142"},{brand:"Ferrari",model:"458 Speciale",gen:"F142"},{brand:"Ferrari",model:"488 GTB",gen:"F142M"},{brand:"Ferrari",model:"488 Pista",gen:"F142M"},{brand:"Ferrari",model:"F8 Tributo",gen:"F142MFL"},{brand:"Ferrari",model:"296 GTB",gen:"F171"},{brand:"Ferrari",model:"296 GTS",gen:"F171"},{brand:"Ferrari",model:"599 GTO",gen:"F141"},{brand:"Ferrari",model:"812 Superfast",gen:"F152M"},{brand:"Ferrari",model:"812 Competizione",gen:"F152M"},{brand:"Ferrari",model:"SF90 Stradale",gen:"F173"},{brand:"Ferrari",model:"SF90 XX Stradale",gen:"F173"},{brand:"Ferrari",model:"Roma",gen:"F169"},{brand:"Ferrari",model:"Roma Spider",gen:"F169"},{brand:"Ferrari",model:"Portofino M",gen:"F164M"},{brand:"Ferrari",model:"Purosangue",gen:"F175"},{brand:"Ferrari",model:"Monza SP1",gen:"2019"},{brand:"Ferrari",model:"Monza SP2",gen:"2019"},{brand:"Ferrari",model:"California T",gen:"F149M"},{brand:"Ferrari",model:"GTC4Lusso",gen:"F151M"},{brand:"Ferrari",model:"12Cilindri",gen:"F167"},
// Lamborghini
{brand:"Lamborghini",model:"Miura",gen:"P400 SV"},{brand:"Lamborghini",model:"Countach",gen:"LP400"},{brand:"Lamborghini",model:"Countach LPI 800-4",gen:"2022"},{brand:"Lamborghini",model:"Diablo",gen:"VT"},{brand:"Lamborghini",model:"Diablo",gen:"SV"},{brand:"Lamborghini",model:"Murci\u00E9lago",gen:"LP640"},{brand:"Lamborghini",model:"Murci\u00E9lago",gen:"LP670 SV"},{brand:"Lamborghini",model:"Aventador",gen:"LP700"},{brand:"Lamborghini",model:"Aventador",gen:"LP750 SV"},{brand:"Lamborghini",model:"Aventador SVJ",gen:"LP770"},{brand:"Lamborghini",model:"Aventador Ultimae",gen:"LP780"},{brand:"Lamborghini",model:"Revuelto",gen:"LB744"},{brand:"Lamborghini",model:"Gallardo",gen:"LP560"},{brand:"Lamborghini",model:"Gallardo Superleggera",gen:"LP570"},{brand:"Lamborghini",model:"Hurac\u00E1n",gen:"LP610"},{brand:"Lamborghini",model:"Hurac\u00E1n Performante",gen:"LP640"},{brand:"Lamborghini",model:"Hurac\u00E1n STO",gen:"LP640"},{brand:"Lamborghini",model:"Hurac\u00E1n Tecnica",gen:"LP640"},{brand:"Lamborghini",model:"Hurac\u00E1n Sterrato",gen:"LP610"},{brand:"Lamborghini",model:"Temerario",gen:"2025"},{brand:"Lamborghini",model:"Urus",gen:"636"},{brand:"Lamborghini",model:"Urus Performante",gen:"636"},{brand:"Lamborghini",model:"Urus SE",gen:"636"},{brand:"Lamborghini",model:"Si\u00E1n",gen:"FKP 37"},{brand:"Lamborghini",model:"Sesto Elemento",gen:"2010"},{brand:"Lamborghini",model:"Veneno",gen:"2013"},
// Maserati
{brand:"Maserati",model:"MC20",gen:"M240"},{brand:"Maserati",model:"MC20 Cielo",gen:"M240"},{brand:"Maserati",model:"GranTurismo",gen:"M240 GT"},{brand:"Maserati",model:"GranTurismo Folgore",gen:"M240 EV"},{brand:"Maserati",model:"GranCabrio Folgore",gen:"M240 EV"},{brand:"Maserati",model:"Quattroporte",gen:"M156"},{brand:"Maserati",model:"Quattroporte Trofeo",gen:"M156 FL"},{brand:"Maserati",model:"Ghibli Trofeo",gen:"M157 FL"},{brand:"Maserati",model:"Levante Trofeo",gen:"M161"},{brand:"Maserati",model:"Grecale",gen:"M182"},{brand:"Maserati",model:"Grecale Folgore",gen:"M182 EV"},{brand:"Maserati",model:"MC12",gen:"2004"},
// Alfa Romeo
{brand:"Alfa Romeo",model:"Giulia",gen:"952"},{brand:"Alfa Romeo",model:"Giulia Quadrifoglio",gen:"952"},{brand:"Alfa Romeo",model:"Stelvio",gen:"949"},{brand:"Alfa Romeo",model:"Stelvio Quadrifoglio",gen:"949"},{brand:"Alfa Romeo",model:"Tonale",gen:"2023"},{brand:"Alfa Romeo",model:"4C",gen:"960"},{brand:"Alfa Romeo",model:"4C Spider",gen:"960"},{brand:"Alfa Romeo",model:"8C Competizione",gen:"2007"},{brand:"Alfa Romeo",model:"Giulietta",gen:"940"},{brand:"Alfa Romeo",model:"Brera",gen:"939"},{brand:"Alfa Romeo",model:"159",gen:"939"},{brand:"Alfa Romeo",model:"33 Stradale",gen:"2024"},
// Fiat / Abarth
{brand:"Fiat",model:"500",gen:"312"},{brand:"Fiat",model:"500e",gen:"332"},{brand:"Fiat",model:"500 Abarth",gen:"312"},{brand:"Fiat",model:"500X",gen:"334"},{brand:"Fiat",model:"Panda",gen:"319"},{brand:"Fiat",model:"Tipo",gen:"356"},{brand:"Fiat",model:"124 Spider",gen:"NF"},{brand:"Abarth",model:"595 Competizione",gen:"312"},{brand:"Abarth",model:"695",gen:"312"},{brand:"Abarth",model:"500e",gen:"332"},
// Pagani
{brand:"Pagani",model:"Zonda C12",gen:"1999"},{brand:"Pagani",model:"Zonda F",gen:"2005"},{brand:"Pagani",model:"Zonda Cinque",gen:"2009"},{brand:"Pagani",model:"Zonda Revolucion",gen:"2013"},{brand:"Pagani",model:"Huayra",gen:"2012"},{brand:"Pagani",model:"Huayra BC",gen:"2016"},{brand:"Pagani",model:"Huayra Roadster BC",gen:"2019"},{brand:"Pagani",model:"Huayra R",gen:"2021"},{brand:"Pagani",model:"Utopia",gen:"2023"},
// Bentley
{brand:"Bentley",model:"Continental GT",gen:"1st Gen"},{brand:"Bentley",model:"Continental GT V8",gen:"3rd Gen"},{brand:"Bentley",model:"Continental GT Speed",gen:"3rd Gen"},{brand:"Bentley",model:"Continental GTC",gen:"3rd Gen"},{brand:"Bentley",model:"Flying Spur",gen:"3rd Gen"},{brand:"Bentley",model:"Flying Spur Mulliner",gen:"3rd Gen"},{brand:"Bentley",model:"Bentayga",gen:"1st Gen"},{brand:"Bentley",model:"Bentayga EWB",gen:"FL"},{brand:"Bentley",model:"Bentayga S",gen:"FL"},{brand:"Bentley",model:"Mulsanne",gen:"2nd Gen"},{brand:"Bentley",model:"Batur",gen:"2023"},{brand:"Bentley",model:"Bacalar",gen:"2020"},
// Rolls-Royce
{brand:"Rolls-Royce",model:"Phantom",gen:"VII"},{brand:"Rolls-Royce",model:"Phantom",gen:"VIII"},{brand:"Rolls-Royce",model:"Phantom EWB",gen:"VIII"},{brand:"Rolls-Royce",model:"Ghost",gen:"RR11"},{brand:"Rolls-Royce",model:"Ghost Black Badge",gen:"RR12"},{brand:"Rolls-Royce",model:"Wraith",gen:"RR05"},{brand:"Rolls-Royce",model:"Wraith Black Badge",gen:"RR05"},{brand:"Rolls-Royce",model:"Dawn",gen:"RR06"},{brand:"Rolls-Royce",model:"Cullinan",gen:"RR31"},{brand:"Rolls-Royce",model:"Cullinan Black Badge",gen:"RR31"},{brand:"Rolls-Royce",model:"Spectre",gen:"RR30"},{brand:"Rolls-Royce",model:"Boat Tail",gen:"2021"},{brand:"Rolls-Royce",model:"Silver Ghost",gen:"1907"},
// Aston Martin
{brand:"Aston Martin",model:"DB7",gen:"1994"},{brand:"Aston Martin",model:"DB9",gen:"2004"},{brand:"Aston Martin",model:"DB11",gen:"2016"},{brand:"Aston Martin",model:"DB12",gen:"2023"},{brand:"Aston Martin",model:"DBS Superleggera",gen:"2018"},{brand:"Aston Martin",model:"DBS 770 Ultimate",gen:"2023"},{brand:"Aston Martin",model:"Vantage",gen:"V8 2018"},{brand:"Aston Martin",model:"Vantage",gen:"V8 2024"},{brand:"Aston Martin",model:"Vanquish",gen:"2024"},{brand:"Aston Martin",model:"Vanquish S",gen:"2017"},{brand:"Aston Martin",model:"Rapide S",gen:"2013"},{brand:"Aston Martin",model:"Valkyrie",gen:"2021"},{brand:"Aston Martin",model:"Valkyrie AMR Pro",gen:"2022"},{brand:"Aston Martin",model:"Valhalla",gen:"2024"},{brand:"Aston Martin",model:"DBX707",gen:"2022"},{brand:"Aston Martin",model:"One-77",gen:"2009"},{brand:"Aston Martin",model:"Vulcan",gen:"2015"},{brand:"Aston Martin",model:"Victor",gen:"2020"},
// McLaren
{brand:"McLaren",model:"F1",gen:"1992"},{brand:"McLaren",model:"F1 GTR",gen:"1995"},{brand:"McLaren",model:"P1",gen:"2013"},{brand:"McLaren",model:"P1 GTR",gen:"2015"},{brand:"McLaren",model:"Speedtail",gen:"2019"},{brand:"McLaren",model:"Senna",gen:"2018"},{brand:"McLaren",model:"Senna GTR",gen:"2019"},{brand:"McLaren",model:"Solus GT",gen:"2023"},{brand:"McLaren",model:"Elva",gen:"2021"},{brand:"McLaren",model:"Sabre",gen:"2021"},{brand:"McLaren",model:"570S",gen:"P13"},{brand:"McLaren",model:"600LT",gen:"P13"},{brand:"McLaren",model:"620R",gen:"P14"},{brand:"McLaren",model:"650S",gen:"P14"},{brand:"McLaren",model:"675LT",gen:"P14"},{brand:"McLaren",model:"720S",gen:"P14"},{brand:"McLaren",model:"720S Spider",gen:"P14"},{brand:"McLaren",model:"765LT",gen:"P14"},{brand:"McLaren",model:"750S",gen:"P14 FL"},{brand:"McLaren",model:"Artura",gen:"HPH"},{brand:"McLaren",model:"Artura Spider",gen:"HPH"},{brand:"McLaren",model:"GT",gen:"P16"},{brand:"McLaren",model:"W1",gen:"2024"},
// Jaguar / Land Rover / Range Rover
{brand:"Jaguar",model:"F-Type R",gen:"X152"},{brand:"Jaguar",model:"F-Type SVR",gen:"X152"},{brand:"Jaguar",model:"F-Pace SVR",gen:"X761"},{brand:"Jaguar",model:"XE SV Project 8",gen:"X760"},{brand:"Jaguar",model:"XF",gen:"X260"},{brand:"Jaguar",model:"XJ",gen:"X351"},{brand:"Jaguar",model:"XKR-S",gen:"X150"},{brand:"Jaguar",model:"I-Pace EV400",gen:"X590"},{brand:"Jaguar",model:"E-Type",gen:"Series 1"},{brand:"Land Rover",model:"Defender 90",gen:"L663"},{brand:"Land Rover",model:"Defender 110 V8",gen:"L663"},{brand:"Land Rover",model:"Defender 130",gen:"L663"},{brand:"Land Rover",model:"Discovery",gen:"L462"},{brand:"Range Rover",model:"SV LWB",gen:"L460"},{brand:"Range Rover",model:"Sport SVR",gen:"L494"},{brand:"Range Rover",model:"Sport",gen:"L461"},{brand:"Range Rover",model:"Velar",gen:"L560"},{brand:"Range Rover",model:"Evoque",gen:"L551"},
// Lotus / Morgan / TVR
{brand:"Lotus",model:"Elise",gen:"S3"},{brand:"Lotus",model:"Exige",gen:"S3"},{brand:"Lotus",model:"Evora GT410",gen:"2019"},{brand:"Lotus",model:"Emira",gen:"V6"},{brand:"Lotus",model:"Emira",gen:"I4"},{brand:"Lotus",model:"Evija",gen:"2024"},{brand:"Morgan",model:"Plus Four",gen:"2020"},{brand:"Morgan",model:"Plus Six",gen:"2020"},{brand:"Morgan",model:"Super 3",gen:"2023"},{brand:"TVR",model:"Sagaris",gen:"2004"},{brand:"TVR",model:"Griffith",gen:"2024"},
// MINI
{brand:"MINI",model:"Cooper S",gen:"F56"},{brand:"MINI",model:"Cooper JCW",gen:"F56"},{brand:"MINI",model:"Cooper SE",gen:"J01"},{brand:"MINI",model:"Countryman JCW",gen:"U25"},{brand:"MINI",model:"Clubman JCW",gen:"F54"},
// Peugeot
{brand:"Peugeot",model:"208",gen:"P21"},{brand:"Peugeot",model:"208 GT",gen:"P21"},{brand:"Peugeot",model:"e-208 GT",gen:"P21"},{brand:"Peugeot",model:"308",gen:"P54"},{brand:"Peugeot",model:"308 GT",gen:"P54"},{brand:"Peugeot",model:"408",gen:"P44"},{brand:"Peugeot",model:"508 PSE",gen:"PF"},{brand:"Peugeot",model:"508",gen:"PF"},{brand:"Peugeot",model:"2008",gen:"P24"},{brand:"Peugeot",model:"3008",gen:"P84"},{brand:"Peugeot",model:"3008",gen:"P64"},{brand:"Peugeot",model:"5008",gen:"P87"},{brand:"Peugeot",model:"205 GTI",gen:"1984"},
// Renault / Alpine / Dacia
{brand:"Renault",model:"Clio",gen:"V"},{brand:"Renault",model:"Megane RS Trophy",gen:"IV"},{brand:"Renault",model:"Megane E-Tech",gen:"EV60"},{brand:"Renault",model:"Arkana",gen:"RJL"},{brand:"Renault",model:"Austral",gen:"HN"},{brand:"Renault",model:"Koleos",gen:"HC"},{brand:"Renault",model:"Rafale",gen:"2024"},{brand:"Renault",model:"5 E-Tech",gen:"2024"},{brand:"Renault",model:"Scenic E-Tech",gen:"2024"},{brand:"Alpine",model:"A110",gen:"AS1"},{brand:"Alpine",model:"A110 S",gen:"AS1"},{brand:"Alpine",model:"A110 R",gen:"AS1"},{brand:"Alpine",model:"A290",gen:"2025"},{brand:"Dacia",model:"Duster",gen:"HJD"},{brand:"Dacia",model:"Sandero Stepway",gen:"BJ"},{brand:"Dacia",model:"Spring",gen:"DJ1"},
// Citroen / DS
{brand:"Citro\u00EBn",model:"C3",gen:"C34"},{brand:"Citro\u00EBn",model:"C3 Aircross",gen:"2024"},{brand:"Citro\u00EBn",model:"C4",gen:"C41"},{brand:"Citro\u00EBn",model:"C4 X",gen:"C41"},{brand:"Citro\u00EBn",model:"C5 X",gen:"C84"},{brand:"Citro\u00EBn",model:"C5 Aircross",gen:"C84"},{brand:"Citro\u00EBn",model:"Berlingo",gen:"K9"},{brand:"DS",model:"3 Crossback",gen:"D34"},{brand:"DS",model:"4",gen:"D44"},{brand:"DS",model:"7 Crossback",gen:"X74"},{brand:"DS",model:"9",gen:"LR"},{brand:"DS",model:"9 E-Tense",gen:"LR"},
// Bugatti
{brand:"Bugatti",model:"Veyron",gen:"16.4"},{brand:"Bugatti",model:"Veyron Super Sport",gen:"16.4"},{brand:"Bugatti",model:"Veyron Grand Sport Vitesse",gen:"16.4"},{brand:"Bugatti",model:"Chiron",gen:"2017"},{brand:"Bugatti",model:"Chiron Sport",gen:"2019"},{brand:"Bugatti",model:"Chiron Pur Sport",gen:"2020"},{brand:"Bugatti",model:"Chiron Super Sport",gen:"300+"},{brand:"Bugatti",model:"Divo",gen:"2019"},{brand:"Bugatti",model:"Centodieci",gen:"2020"},{brand:"Bugatti",model:"Bolide",gen:"2021"},{brand:"Bugatti",model:"Mistral",gen:"2024"},{brand:"Bugatti",model:"Tourbillon",gen:"2026"},
// Volvo
{brand:"Volvo",model:"S60",gen:"Z"},{brand:"Volvo",model:"S60 T8 Polestar",gen:"Z"},{brand:"Volvo",model:"S90",gen:"P"},{brand:"Volvo",model:"V60",gen:"Z"},{brand:"Volvo",model:"V60 Cross Country",gen:"Z"},{brand:"Volvo",model:"V90 Cross Country",gen:"P"},{brand:"Volvo",model:"XC40",gen:"XZ"},{brand:"Volvo",model:"XC40 Recharge",gen:"XZ EV"},{brand:"Volvo",model:"XC60",gen:"SPA"},{brand:"Volvo",model:"XC60 B6 R-Design",gen:"SPA FL"},{brand:"Volvo",model:"XC90",gen:"SPA"},{brand:"Volvo",model:"XC90 T8 Recharge",gen:"SPA"},{brand:"Volvo",model:"EX30",gen:"2024"},{brand:"Volvo",model:"EX90",gen:"2024"},{brand:"Volvo",model:"EM90",gen:"2024"},
// Polestar / Saab / Koenigsegg
{brand:"Polestar",model:"1",gen:"2020"},{brand:"Polestar",model:"2",gen:"BST 2023"},{brand:"Polestar",model:"3",gen:"2024"},{brand:"Polestar",model:"4",gen:"2024"},{brand:"Saab",model:"9-3 Aero",gen:"YS3F"},{brand:"Saab",model:"9-5 Aero",gen:"YS3G"},{brand:"Saab",model:"900 Turbo",gen:"Classic"},{brand:"Koenigsegg",model:"CC8S",gen:"2002"},{brand:"Koenigsegg",model:"CCX",gen:"2006"},{brand:"Koenigsegg",model:"Agera R",gen:"2012"},{brand:"Koenigsegg",model:"Agera RS",gen:"2017"},{brand:"Koenigsegg",model:"One:1",gen:"2014"},{brand:"Koenigsegg",model:"Regera",gen:"2016"},{brand:"Koenigsegg",model:"Jesko",gen:"2020"},{brand:"Koenigsegg",model:"Jesko Absolut",gen:"2020"},{brand:"Koenigsegg",model:"Gemera",gen:"2024"},{brand:"Koenigsegg",model:"CC850",gen:"2023"},
// smart
{brand:"smart",model:"#1 Brabus",gen:"HX11"},{brand:"smart",model:"#3 Brabus",gen:"HX21"},{brand:"smart",model:"forfour",gen:"W453"},
// Skoda
{brand:"\u0160koda",model:"Octavia RS",gen:"NX"},{brand:"\u0160koda",model:"Octavia",gen:"A8"},{brand:"\u0160koda",model:"Superb",gen:"3V FL"},{brand:"\u0160koda",model:"Superb",gen:"NX"},{brand:"\u0160koda",model:"Kodiaq RS",gen:"NS7"},{brand:"\u0160koda",model:"Kodiaq",gen:"NS"},{brand:"\u0160koda",model:"Karoq",gen:"NU"},{brand:"\u0160koda",model:"Kamiq",gen:"NW"},{brand:"\u0160koda",model:"Fabia",gen:"PJ"},{brand:"\u0160koda",model:"Enyaq iV",gen:"EV"},{brand:"\u0160koda",model:"Enyaq Coup\u00E9 RS",gen:"EV"},
// SEAT / CUPRA
{brand:"SEAT",model:"Leon",gen:"KL"},{brand:"SEAT",model:"Ibiza",gen:"KJ"},{brand:"SEAT",model:"Ateca",gen:"KH"},{brand:"CUPRA",model:"Leon",gen:"KL"},{brand:"CUPRA",model:"Formentor VZ5",gen:"KM"},{brand:"CUPRA",model:"Born",gen:"J1"},{brand:"CUPRA",model:"Tavascan",gen:"2024"},{brand:"CUPRA",model:"Ateca",gen:"KH"},
// Geely / Lynk
{brand:"Geely",model:"Coolray",gen:"SX11"},{brand:"Geely",model:"Atlas",gen:"NL3"},{brand:"Geely",model:"Atlas Pro",gen:"NL3A"},{brand:"Geely",model:"Monjaro",gen:"KX11"},{brand:"Geely",model:"Tugella",gen:"FY11"},{brand:"Geely",model:"Preface",gen:"V"},{brand:"Geely",model:"Emgrand",gen:"L4"},{brand:"Geely",model:"Okavango",gen:"VX11"},{brand:"Geely",model:"Geometry C",gen:"EV"},{brand:"Lynk & Co",model:"01",gen:"CX11"},{brand:"Lynk & Co",model:"03+",gen:"CE11"},{brand:"Lynk & Co",model:"05",gen:"FE11"},{brand:"Lynk & Co",model:"09",gen:"KX11"},
// Chery / Exeed
{brand:"Chery",model:"Tiggo 4 Pro",gen:"T17"},{brand:"Chery",model:"Tiggo 7 Pro",gen:"T18"},{brand:"Chery",model:"Tiggo 7 Pro Max",gen:"T18"},{brand:"Chery",model:"Tiggo 8 Pro",gen:"T26"},{brand:"Chery",model:"Tiggo 8 Pro Max",gen:"T26"},{brand:"Chery",model:"Arrizo 8",gen:"E6"},{brand:"Chery",model:"Omoda 5",gen:"C5"},{brand:"Chery",model:"Omoda 7",gen:"C7"},{brand:"Chery",model:"Jaecoo J7",gen:"EV"},{brand:"Exeed",model:"TXL",gen:"M79"},{brand:"Exeed",model:"VX",gen:"M99"},{brand:"Exeed",model:"LX",gen:"V81"},{brand:"Exeed",model:"RX",gen:"M82"},
// Haval / GWM / Tank / WEY
{brand:"Haval",model:"Jolion",gen:"B06"},{brand:"Haval",model:"F7",gen:"B03"},{brand:"Haval",model:"F7x",gen:"B04"},{brand:"Haval",model:"Dargo",gen:"B07"},{brand:"Haval",model:"H6",gen:"B30"},{brand:"Haval",model:"H9",gen:"2022 FL"},{brand:"GWM",model:"ORA Cat",gen:"ES11"},{brand:"GWM",model:"Poer",gen:"P01"},{brand:"Tank",model:"300",gen:"N3B"},{brand:"Tank",model:"500",gen:"N5B"},{brand:"Tank",model:"700",gen:"N7B"},{brand:"WEY",model:"Mocha",gen:"W78"},{brand:"WEY",model:"Coffee 01",gen:"PHEV"},{brand:"WEY",model:"Coffee 02",gen:"PHEV"},
// Zeekr
{brand:"Zeekr",model:"001",gen:"ZA11"},{brand:"Zeekr",model:"001 FR",gen:"ZA11"},{brand:"Zeekr",model:"007",gen:"ZB11"},{brand:"Zeekr",model:"009",gen:"ZM11"},{brand:"Zeekr",model:"X",gen:"ZX11"},{brand:"Zeekr",model:"Mix",gen:"2025"},
// BYD
{brand:"BYD",model:"Han EV",gen:"2022"},{brand:"BYD",model:"Han DM-i",gen:"2022"},{brand:"BYD",model:"Tang EV600",gen:"2022"},{brand:"BYD",model:"Tang DM-p",gen:"2023"},{brand:"BYD",model:"Song Plus DM-i",gen:"2023"},{brand:"BYD",model:"Song Plus EV",gen:"2023"},{brand:"BYD",model:"Qin Plus DM-i",gen:"2023"},{brand:"BYD",model:"Seal",gen:"2023"},{brand:"BYD",model:"Seal U DM-i",gen:"2024"},{brand:"BYD",model:"Dolphin",gen:"2023"},{brand:"BYD",model:"Atto 3",gen:"2022"},{brand:"BYD",model:"Yangwang U8",gen:"2023"},{brand:"BYD",model:"Yangwang U9",gen:"2024"},{brand:"BYD",model:"Denza N7",gen:"2023"},{brand:"BYD",model:"Denza D9",gen:"2023"},{brand:"BYD",model:"Fang Cheng Bao Leopard 5",gen:"2024"},
// Hongqi
{brand:"Hongqi",model:"H5",gen:"2023"},{brand:"Hongqi",model:"H9",gen:"2020"},{brand:"Hongqi",model:"H9+",gen:"2023"},{brand:"Hongqi",model:"E-HS9",gen:"2021"},{brand:"Hongqi",model:"L5",gen:"Parade"},{brand:"Hongqi",model:"LS7",gen:"2022"},{brand:"Hongqi",model:"E001",gen:"2025"},{brand:"Hongqi",model:"EH7",gen:"2024"},
// Li Auto
{brand:"Li Auto",model:"L6",gen:"2024"},{brand:"Li Auto",model:"L7",gen:"Max"},{brand:"Li Auto",model:"L8",gen:"Pro"},{brand:"Li Auto",model:"L9",gen:"Max"},{brand:"Li Auto",model:"MEGA",gen:"EV 2024"},{brand:"Li Auto",model:"ONE",gen:"2020"},
// XPeng
{brand:"XPeng",model:"P5",gen:"2022"},{brand:"XPeng",model:"P7",gen:"2020"},{brand:"XPeng",model:"P7i",gen:"2023"},{brand:"XPeng",model:"G3i",gen:"2021"},{brand:"XPeng",model:"G6",gen:"2023"},{brand:"XPeng",model:"G9",gen:"2022"},{brand:"XPeng",model:"X9",gen:"2024"},{brand:"XPeng",model:"Mona M03",gen:"2024"},
// NIO
{brand:"NIO",model:"ES6",gen:"2023"},{brand:"NIO",model:"ES7",gen:"2022"},{brand:"NIO",model:"ES8",gen:"2022"},{brand:"NIO",model:"ET5",gen:"2022"},{brand:"NIO",model:"ET5 Touring",gen:"2023"},{brand:"NIO",model:"ET7",gen:"2022"},{brand:"NIO",model:"EC6",gen:"2023"},{brand:"NIO",model:"EC7",gen:"2023"},{brand:"NIO",model:"EP9",gen:"2016"},{brand:"NIO",model:"EL8",gen:"2024"},
// Changan / Dongfeng / Avatr / GAC / FAW / JAC
{brand:"Changan",model:"UNI-T",gen:"2021"},{brand:"Changan",model:"UNI-V",gen:"2022"},{brand:"Changan",model:"UNI-K",gen:"iDD"},{brand:"Changan",model:"CS75 Plus",gen:"2023"},{brand:"Changan",model:"CS55 Plus",gen:"2023"},{brand:"Changan",model:"Deepal S7",gen:"EV"},{brand:"Changan",model:"Deepal SL03",gen:"EV"},{brand:"Dongfeng",model:"Mengshi 917",gen:"EV"},{brand:"Dongfeng",model:"Aeolus Haohan",gen:"2023"},{brand:"Dongfeng",model:"Voyah Free",gen:"EV"},{brand:"Dongfeng",model:"Voyah Dreamer",gen:"EV"},{brand:"Avatr",model:"11",gen:"EV"},{brand:"Avatr",model:"12",gen:"EV"},{brand:"GAC",model:"Aion S Plus",gen:"EV"},{brand:"GAC",model:"Aion V Plus",gen:"EV"},{brand:"GAC",model:"Aion LX Plus",gen:"EV"},{brand:"GAC",model:"Aion Hyper GT",gen:"EV"},{brand:"GAC",model:"Aion Hyper SSR",gen:"EV"},{brand:"FAW",model:"Bestune T77",gen:"2022"},{brand:"FAW",model:"Bestune T99",gen:"2021"},{brand:"JAC",model:"JS4",gen:"2022"},{brand:"JAC",model:"JS6",gen:"2023"},
// Lotus (China) / Xiaomi
{brand:"Lotus",model:"Eletre",gen:"EV 2023"},{brand:"Lotus",model:"Eletre R",gen:"EV 2023"},{brand:"Lotus",model:"Emeya",gen:"EV 2024"},{brand:"Lotus",model:"Emeya R",gen:"EV 2024"},{brand:"Xiaomi",model:"SU7",gen:"Standard"},{brand:"Xiaomi",model:"SU7 Pro",gen:"2024"},{brand:"Xiaomi",model:"SU7 Max",gen:"2024"},{brand:"Xiaomi",model:"SU7 Ultra",gen:"2025"},
// Acura
{brand:"Acura",model:"Integra Type S",gen:"DE"},{brand:"Acura",model:"TLX Type S",gen:"UB3"},{brand:"Acura",model:"MDX Type S",gen:"YE1"},{brand:"Acura",model:"RDX",gen:"TC"},{brand:"Acura",model:"NSX Type S",gen:"NC1"},{brand:"Acura",model:"ZDX Type S",gen:"EV"},{brand:"Acura",model:"RSX Type S",gen:"DC5"},
// Exotics
{brand:"Rimac",model:"Nevera",gen:"2023"},{brand:"Rimac",model:"C_Two",gen:"2021"},{brand:"SSC",model:"Tuatara",gen:"2020"},{brand:"Hennessey",model:"Venom F5",gen:"2021"},{brand:"Hennessey",model:"Venom GT",gen:"2014"},{brand:"W Motors",model:"Lykan HyperSport",gen:"2014"},{brand:"W Motors",model:"Fenyr SuperSport",gen:"2018"},{brand:"Czinger",model:"21C",gen:"2023"},{brand:"De Tomaso",model:"P72",gen:"2024"},{brand:"GMA",model:"T.50",gen:"2022"},{brand:"GMA",model:"T.33",gen:"2024"},{brand:"Pininfarina",model:"Battista",gen:"2023"},{brand:"Spyker",model:"C8 Aileron",gen:"2009"},{brand:"Wiesmann",model:"Project Thunderball",gen:"2024"},{brand:"Zenvo",model:"TSR-S",gen:"2020"},{brand:"Zenvo",model:"Aurora",gen:"2024"},{brand:"Apollo",model:"Intensa Emozione",gen:"2019"},{brand:"Dallara",model:"Stradale",gen:"2018"},{brand:"Radical",model:"SR10",gen:"2022"},{brand:"KTM",model:"X-Bow GT-XR",gen:"2024"},{brand:"Caterham",model:"Seven 620R",gen:"2016"},{brand:"Ariel",model:"Atom 4",gen:"2019"},{brand:"Ariel",model:"Nomad 2",gen:"2021"},{brand:"BAC",model:"Mono R",gen:"2020"},{brand:"Donkervoort",model:"F22",gen:"2023"},{brand:"Noble",model:"M500",gen:"2024"},{brand:"Praga",model:"Bohema",gen:"2023"},{brand:"Singer",model:"DLS Turbo",gen:"911 Reimagined"},{brand:"RUF",model:"CTR Anniversary",gen:"2017"},{brand:"RUF",model:"SCR",gen:"2020"},{brand:"Lister",model:"Stealth",gen:"F-Pace"},{brand:"Hispano Suiza",model:"Carmen Boulogne",gen:"2022"},{brand:"Gordon Murray",model:"T.50",gen:"V12 2022"},{brand:"Fisker",model:"Ocean",gen:"2023"},{brand:"VinFast",model:"VF 9",gen:"2023"},{brand:"VinFast",model:"VF 8",gen:"2023"},
// Classics
{brand:"Toyota",model:"AE86",gen:"Sprinter Trueno"},{brand:"Nissan",model:"240SX",gen:"S13"},{brand:"Nissan",model:"Stagea",gen:"WC34"},{brand:"Honda",model:"CR-X",gen:"EF"},{brand:"Mazda",model:"Cosmo Sport",gen:"L10A"},{brand:"Mercedes-Benz",model:"300 SL",gen:"Gullwing"},{brand:"Porsche",model:"356",gen:"Speedster"},{brand:"Ford",model:"GT40",gen:"1966"},{brand:"Chevrolet",model:"Impala SS",gen:"1967"},{brand:"Dodge",model:"Charger R/T",gen:"1969"},{brand:"Plymouth",model:"Barracuda",gen:"1970"},{brand:"Pontiac",model:"GTO",gen:"1969"},{brand:"Shelby",model:"Cobra 427",gen:"1965"},{brand:"BMW",model:"2002 Turbo",gen:"1973"},{brand:"Lancia",model:"Delta HF Integrale",gen:"1991"},{brand:"Lancia",model:"Stratos",gen:"1973"},{brand:"Alpine",model:"A310",gen:"V6"},{brand:"Datsun",model:"240Z",gen:"S30"},{brand:"Toyota",model:"2000GT",gen:"MF10"},{brand:"Ferrari",model:"Testarossa",gen:"1984"},{brand:"Lamborghini",model:"LM002",gen:"1986"},{brand:"DeLorean",model:"DMC-12",gen:"1981"},{brand:"Saleen",model:"S7",gen:"Twin Turbo"},{brand:"Vector",model:"W8",gen:"1990"},{brand:"Iso",model:"Grifo",gen:"GL"},{brand:"Jensen",model:"Interceptor",gen:"FF"},{brand:"Citro\u00EBn",model:"DS",gen:"21 Pallas"},{brand:"Citro\u00EBn",model:"SM",gen:"1970"},{brand:"Tatra",model:"T87",gen:"1936"}
];
